# Generated by Django 5.0.6 on 2024-05-20 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_remove_person_phone_number_person_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialitys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cheffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='cheffs')),
                ('password', models.CharField(max_length=50)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.specialitys')),
            ],
        ),
    ]
