# Generated by Django 5.0.6 on 2024-05-18 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.SmallIntegerField()),
                ('chairs_number', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_time_end', models.DateTimeField(auto_created=True)),
                ('usage_time_start', models.DateTimeField(auto_created=True)),
                ('booking_number', models.SmallIntegerField()),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('reservation_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
                ('table_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.table')),
            ],
        ),
        migrations.AddField(
            model_name='table',
            name='table_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.tabletype'),
        ),
    ]
